### ISSUE TITLE
ImportError: No module named antlr4

### ISSUE THREAD

**Issue by sligocki** [adamyedidia/parsimony#1]
Looks like you depend on ANTLR4, maybe add installation instructions to the README?

I'm guessing `pip install antlr4-python2-runtime` from http://www.antlr.org/download.html.

```
$ python laconic_interpreter.py goldbach
Traceback (most recent call last):
  File "laconic_interpreter.py", line 1, in <module>
    from antlr4 import *
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 181, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
ImportError: No module named antlr4
```

PS: Very exciting to see your result :)

**Comment by adamyedidia** [comment]
Yes, you are right. Thanks for the heads-up!

**Comment by ahmedohadi** [comment]
hello, 

i'm having same problem and i assure you that i already have the runtime thing installed already because when i tried to re-installed it, i've got this messages on the terminal "requirement is already satisfied" along with its path.

what other solutions might be to solve "ImportError: No module named TripleGen" :( 

appreciate your quick reply! & thanks a lot!

**Comment by xandaaah** [comment]
If anyone comes here, just know `pip install antlr4-python3-runtime` for python3, and `pip install antlr4-python2-runtime` for python2.
